title: Visualizing Caribbean Literature
url: ""
baseurl: "/vcl"
author:
  name: Create Caribbean Research Institute
  email: info@createcaribbean.org
  github: createcaribbean
  twitter: createcaribbean

logo: '/assets/img/CreateLogo.png'

description: > # this means to ignore newlines until "show_excerpts:"
 Visualizing Caribbean Literature is an interactive database of more than 3,000 literary works about the Caribbean experience or by writers identifying as Caribbean people. The database inlcudes authors and titles that represents the diversity of the body of work that is Caribbean literature. 

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-relative-links
 


# Google Analytics Tracking (optional)
ga_tracking:
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

permalink: pretty


exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "graphic_templates",
    "*.py",
    "*.sh",
    "*.yml"
  ]

kramdown:
  syntax_highlighter_opts:
    block:
    line_numbers: false

# Guideline:https://www.digitalocean.com/community/tutorials/jekyll-compress-html0
compress_html:
  clippings: all
  comments: all
  endings: []
  startings: []
  blanklines: true
  profile: false
  # ignore:
  #   envs: all

#COLLECTIONS
collections:
  authors:
    output: true
    permalink: /authors/:name
  alphabet_index:
    output: true
    permalink: /authors/index/:name
  genres:
    output: true
    permalink: /genres/:name
  languages:
    output: true
    permalink: /languages/:name
  countries:
    output: true
    permalink: /countries/:name
  pagination_index:
    output: true
    permalink: /page/:name